export const demoTrades = [
    {
        id: "demo-1",
        account_id: "demo-account",
        profile_id: "demo-user",
        symbol: "EURUSD",
        direction: "long",
        status: "closed",
        entry_price: 1.0545,
        exit_price: 1.0590,
        volume: 1.5,
        pnl_gross: 450,
        commission: 15,
        pnl_net: 435,
        entry_date: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
        exit_date: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
        rr_ratio: 2.5,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: "demo-2",
        account_id: "demo-account",
        profile_id: "demo-user",
        symbol: "US30",
        direction: "short",
        status: "closed",
        entry_price: 38400,
        exit_price: 38300,
        volume: 2.0,
        pnl_gross: 200,
        commission: 10,
        pnl_net: 190,
        entry_date: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
        exit_date: new Date().toISOString(),
        rr_ratio: 1.8,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: "demo-3",
        account_id: "demo-account",
        profile_id: "demo-user",
        symbol: "XAUUSD",
        direction: "long",
        status: "closed",
        entry_price: 2025.5,
        exit_price: 2018.0,
        volume: 0.5,
        pnl_gross: -375,
        commission: 5,
        pnl_net: -380,
        entry_date: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
        exit_date: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
        rr_ratio: -1.0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: "demo-4",
        account_id: "demo-account",
        profile_id: "demo-user",
        symbol: "BTCUSD",
        direction: "long",
        status: "closed",
        entry_price: 61000,
        exit_price: 64000,
        volume: 0.2,
        pnl_gross: 600,
        commission: 20,
        pnl_net: 580,
        entry_date: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
        exit_date: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
        rr_ratio: 3.1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    }
]
