"use client"

import { useState } from "react"
import { supabase } from "@/lib/supabase"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { toast } from "sonner"
import { Loader2, Database } from "lucide-react"

export default function SeedPage() {
    const [seeding, setSeeding] = useState(false)

    const generateRandomTrade = (accountId: string, userId: string, date: Date) => {
        const symbols = ["EURUSD", "GBPUSD", "XAUUSD", "US30", "NAS100", "BTCUSD"]
        const symbol = symbols[Math.floor(Math.random() * symbols.length)]
        const direction = Math.random() > 0.5 ? "LONG" : "SHORT"

        // Base price simulation
        let entryPrice = 0
        if (symbol.includes("USD") && symbol.length === 6) entryPrice = 1.05 + Math.random() * 0.10
        if (symbol === "XAUUSD") entryPrice = 2000 + Math.random() * 100
        if (symbol === "US30") entryPrice = 38000 + Math.random() * 1000
        if (symbol === "NAS100") entryPrice = 17000 + Math.random() * 500
        if (symbol === "BTCUSD") entryPrice = 65000 + Math.random() * 5000

        const isWin = Math.random() > 0.45 // 55% win rate
        const risk = 100 + Math.random() * 50 // Risk $100-$150
        const reward = risk * (1 + Math.random() * 2) // RR 1:1 to 1:3

        const pnl = isWin ? reward : -risk
        const fees = 5 + Math.random() * 5
        const netPnl = pnl - fees

        // Simulate exit price based on pnl/quantity
        // Simplified: just setting quantity 1 for logic mostly
        const quantity = 1

        let exitPrice = entryPrice
        // rough estimate diff
        const diff = Math.abs(pnl) / 10000 // scaling factor for price diff visualization

        if (direction === "LONG") {
            exitPrice = isWin ? entryPrice * 1.002 : entryPrice * 0.998
        } else {
            exitPrice = isWin ? entryPrice * 0.998 : entryPrice * 1.002
        }

        const entryDate = new Date(date)
        // exit 1 hour to 3 days later
        const durationHours = 1 + Math.random() * 72
        const exitDate = new Date(entryDate.getTime() + durationHours * 60 * 60 * 1000)

        return {
            user_id: userId,
            account_id: accountId,
            symbol,
            direction,
            entry_date: entryDate.toISOString(),
            exit_date: exitDate.toISOString(),
            entry_price: parseFloat(entryPrice.toFixed(5)),
            exit_price: parseFloat(exitPrice.toFixed(5)),
            quantity,
            fees: parseFloat(fees.toFixed(2)),
            pnl_gross: parseFloat(pnl.toFixed(2)),
            pnl_net: parseFloat(netPnl.toFixed(2)),
            status: 'CLOSED',
            setup_tags: isWin ? ['Trend', 'Breakout'] : ['Choppy', 'Reversal'],
            notes: 'Generated by seeder'
        }
    }

    const handleSeed = async () => {
        setSeeding(true)
        try {
            const { data: { user } } = await supabase.auth.getUser()
            if (!user) throw new Error("Usuário não autenticado")

            // Get first account
            let { data: accounts } = await supabase.from('accounts').select('id').limit(1)
            let accountId = accounts?.[0]?.id

            if (!accountId) {
                // create default if needed
                const { data: newAcc, error } = await supabase.from('accounts').insert({
                    user_id: user.id,
                    name: 'Demo Seed',
                    currency: 'USD',
                }).select().single()
                if (error) throw error
                accountId = newAcc.id
            }

            const trades = []
            const startDate = new Date()
            startDate.setDate(startDate.getDate() - 90) // 3 months history

            for (let i = 0; i < 50; i++) {
                const date = new Date(startDate.getTime() + Math.random() * (90 * 24 * 60 * 60 * 1000))
                trades.push(generateRandomTrade(accountId, user.id, date))
            }

            // Sort by date to look realistic
            trades.sort((a, b) => new Date(a.entry_date).getTime() - new Date(b.entry_date).getTime())

            const { error: insertError } = await supabase.from('trades').insert(trades)
            if (insertError) throw insertError

            toast.success("50 Trades gerados com sucesso!")

        } catch (error: any) {
            toast.error("Erro ao gerar trades: " + error.message)
        } finally {
            setSeeding(false)
        }
    }

    const handleClear = async () => {
        if (!confirm("Tem certeza? Isso apagará TODOS os seus trades!")) return
        setSeeding(true)
        try {
            const { error } = await supabase.from('trades').delete().neq('id', '00000000-0000-0000-0000-000000000000') // Delete all
            if (error) throw error
            toast.success("Trades apagados.")
        } catch (e: any) {
            toast.error(e.message)
        } finally {
            setSeeding(false)
        }
    }

    return (
        <div className="flex h-screen items-center justify-center bg-gray-50 p-4">
            <Card className="w-full max-w-md">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <Database className="h-5 w-5" />
                        Gerador de Dados (Seed)
                    </CardTitle>
                    <CardDescription>
                        Gere dados fictícios para testar os gráficos e relatórios.
                    </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                    <Button
                        className="w-full"
                        onClick={handleSeed}
                        disabled={seeding}
                    >
                        {seeding ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
                        Gerar 50 Trades Aleatórios
                    </Button>

                    <Button
                        variant="destructive"
                        className="w-full"
                        onClick={handleClear}
                        disabled={seeding}
                    >
                        Apagar Todos os Trades
                    </Button>

                    <Button variant="outline" className="w-full" onClick={() => window.location.href = '/'}>
                        Voltar ao Dashboard
                    </Button>
                </CardContent>
            </Card>
        </div>
    )
}
